- binding.gyp
- lib/utils.js
Awesome project! I just added some fixes for Mac OS compilation. #2
> Support for Mac OS

- cc/core/Mat.cc
- cc/core/Mat.h
- doc/README.md
- doc/core/Mat.md
- test/tests/core/Mat/Mat.test.js
- test/tests/core/Mat/imgprocTests.js
Implements bindings for: Sobel, Scharr as requested in #14, and Laplacian.
> sobel, scharr, laplacian

- .codecov.yml
- cc/modules/io/io.cc
- cc/modules/io/io.h
added bindings to moveWindow as requested in #18 + destroyWindow, destroyAllWindows
> added moveWindow, destroyWindow, destroyAllWindows

- cc/modules/tracking/MultiTracker.cc
> fix for const char* to cv string conversion

- .travis.yml
- ci/opencv3.0-contrib/Dockerfile
- ci/opencv3.1-contrib/Dockerfile
- ci/opencv3.3-contrib/Dockerfile
- lib/utils.js
- package.json
> disable contrib tracking module by default until all contrib versions are supported

- binding.gyp
- cc/modules/ximgproc/SuperpixelSLIC.cc
- cc/modules/ximgproc/SuperpixelSLIC.h
- cc/modules/ximgproc/ximgproc.cc
Just added a wrapper for the cv::ximgproc::SuperpixelSLIC Class.
> Add SuperpixelSLIC functionality

- cc/modules/imgproc/imgproc.cc
- cc/modules/imgproc/imgproc.h
- adding support for the two methods getAffineTransform and getPerspectiveTransform
- someone (probably me when I get time), needs to come back and update the docs and write tests
> Adding getAffineTransform and getPerspectiveTransform

- cc/modules/dnn/Net.cc
- cc/modules/dnn/dnn.cc
- cc/opencv4nodejs.cc
> fix for dnn link error with opencv world

- .appveyor.yml
- .gitignore
> add appveyor

- cc/modules/io/io.cc
- cc/modules/io/io.h
- doc/io/io.md
- test/tests/modules/io/io.test.js
Added optional flags parameter to imread and imwrite #78
> imread and imwrite flags

- cc/core/Mat.cc
- cc/core/Mat.h
- cc/cvTypes/cvTypes.cc
- doc/core/Mat.md
- test/tests/core/Mat/Mat.test.js
#96
Added the following bindings:
- flip
- flipAsync
- rotate
- rotateAsync
> bindings for flip, rotate

- cc/core/MatImgproc.cc
- test/tests/core/Mat/imgprocTests.js
Fixed resize bug issued in #103  and more meaningful testcase.
> fixed resize binding

- cc/core/MatImgproc.cc
- test/tests/core/Mat/Mat.test.js
inrange can be used on a single channeled Mat with scalars now #136
> support inrange with scalars

- README.md
> Update imwriteAsync documentation

- cc/core/Mat.cc
- cc/core/Mat.h
- test/tests/core/Mat/Mat.test.js
#144 
PR adds the following bindings:
- convertScaleAbs
- convertScaleAbsAsync
- sum
- sumAsync
> added sum and convertScaleAbs

- cc/core/MatImgproc.cc
- cc/core/Rect.cc
- cc/core/Rect.h
- test/tests/core/Rect.test.js
PR adds the bindings for Rect:
- or
- and
- toSquare
- toSquareAsync
- rescale
- rescaleAsync
+ fix for #147
> added following methods for Rect class: or, and, toSquare, rescale

- cc/core/MatImgproc.cc
- cc/core/MatImgproc.h
- cc/core/Rect.cc
- cc/core/RotatedRect.h
- test/tests/core/Mat/imgprocTests.js
- test/utils/matTestUtils.js
#149
PR adds the bindings for:
- drawPolylines
- drawFillPoly
- drawFillConvexPoly
- drawArrowedLine
- drawRectangle with Rect
- drawEllipse with center, axes and angles
> new drawing functions

- README.md
Added some information in the read me about base64 import/export of images.
Heavily inspired from Issue #70 .
If this PR isn't in the the same spirit as your docs, feel free to change as necessary. 
This is my first PR, if I didn't follow any good practices, please let me know.
Best,
Leon
> Added information about base64 import/export

- binding.gyp
- cc/modules/features2d/descriptorMatchingKnn.cc
- cc/modules/features2d/descriptorMatchingKnn.h
- cc/modules/features2d/features2d.cc
Hey, thanks for this library, keep up the good work!
I needed knn match for my project so tried to implement it. It's just a copy of DescriptorMatching with some modifications.
There is an another input k - number of nearest neighbors. The function returns 	`std::vector<std::vector<cv::DMatch>>`
> DescriptorMatchingKnn

- cc/core/Mat.cc
- cc/core/Mat.h
- cc/core/MatImgproc.cc
- cc/core/core.cc
- cc/core/core.h
- cc/cvTypes/imgprocConstants.cc
- lib/typings/Mat.d.ts
- lib/typings/cv.d.ts
- package-lock.json
- test/tests/core/Mat/Mat.test.js
- test/tests/core/core.test.js
#192 
- cartToPolar
- polarToCart
- mat.pushBack 
- mat.popBack
> cartToPolar, polarToCart, mat.pushBack, mat.popBack

- cc/modules/features2d/detectors/MSERDetector.cc
- cc/modules/features2d/detectors/MSERDetector.h
Adds functions
MSERDetector.detectRegions( img )
MSERDetector.detectRegionsAsync( img, function( err, return ){ } );
Returns a structure { msers: [ array of Point2 arrays ], bboxes:[ array of bounding Rects ] } 
as per Opencv docs.
usage something like:
var options = { delta:5, minArea:60, maxArea:14400,maxVariation:0.25,minDiversity:0.2,
maxEvolution:200,areaThreshold:1.01,minMargin:0.003,edgeBlurSize:5 };
var det = new cv.MSERDetector( options );
det.detectRegionsAsync(img, function (err, result) { 
console.log(util.inspect(result));
}
> Add functions to MSERDetector for detectRegions, Sync and Async

- cc/core/coreUtils.h
- lib/typings/Mat.d.ts
- test/tests/core/Mat/operatorTests.js
Hi there!
I've added `log` to the `Mat` method list.
> Add: Mat.log

- cc/core/Mat.cc
- cc/core/Mat.h
- lib/typings/Mat.d.ts
- test/tests/core/Mat/imgprocTests.js
Hi there!
I've added `goodFeaturesToTrack` and `goodFeaturesToTrackAsync` to the `Mat` method list.
I have one question though, the output of the function is a `Nx1 2channel Mat` which might be a bit confusing. Should I cast it in an array of `Point2f` or keep it true to the original & opencv's documentation? 
[opencv's method implementation](https://github.com/opencv/opencv/blob/d9f720a679f91beb4f09490947f4e6ee597b6d8f/modules/imgproc/src/featureselect.cpp#L515)
[opencv's method documentation](https://docs.opencv.org/3.4.1/dd/d1a/group__imgproc__feature.html#ga1d6bb77486c8f92d79c8793ad995d541)
> Add: Mat.goodFeaturesToTrack

- binding.gyp
- cc/cvTypes/cvTypes.cc
- cc/cvTypes/photoConstants.cc
- cc/cvTypes/photoConstants.h
- cc/modules/photo.cc
- cc/modules/photo.h
- lib/typings/constants.d.ts
- lib/typings/cv.d.ts
- test/tests/modules/photo/photo.test.js
> [WIP] Add: photo inpaint

- cc/core/Mat.cc
- cc/core/Mat.h
- cc/core/MatImgproc.cc
- cc/core/MatImgproc.h
- lib/typings/Mat.d.ts
- test/tests/core/Mat/Mat.test.js
- test/tests/core/Mat/imgprocTests.js
PR adds bindings to integral #240  and meanStdDev #224
> integral + meanStdDev

- binding.gyp
Related to this [issue](https://github.com/justadudewhohacks/opencv4nodejs/issues/204) I have added link settings in a condition section.
> Add relative path to opencv-build/lib folder for linker

- cc/core/Mat.cc
- cc/core/Mat.h
- cc/core/MatBindings.h
- cc/core/coreUtils.h
- lib/typings/Mat.d.ts
- test/tests/core/Mat/Mat.test.js
fixed mat mean to return a Vec4 with mean for each channel #267
> fixed mat mean to return a Vec4 with mean for each channel

- cc/core/Mat.cc
- cc/core/Mat.h
- cc/core/MatBindings.h
- lib/typings/Mat.d.ts
- test/tests/core/Mat/Mat.test.js
> added copyMakeBorder

- cc/core/core.cc
- cc/core/core.h
- lib/typings/cv.d.ts
- test/tests/core/core.test.js
This allow us to get OpenCV's build information in JS. Can be very useful for debugging purposes or to implement an issue template.
> Implemented getBuildInformation

- cc/modules/io/VideoWriter.cc
fix for #290, issue was not returning the handle to the VideoWriter wrap in the constructor
> fixed VideoWriter constructor #290

- cc/modules/io/ioBindings.h
#326 and [this](https://github.com/justadudewhohacks/opencv-electron/issues/13)
> fix imencode crashes in electron when buffer is released

- cc/core/MatImgprocBindings.h
- lib/typings/Mat.d.ts
- test/tests/core/Mat/imgprocTests.js
> fixed border value for warping methods

- cc/core/Mat.cc
ref: https://github.com/justadudewhohacks/opencv4nodejs/issues/348
> fixed arguments checking of `Mat::Normalize`

- cc/core/Mat.cc
- cc/core/MatImgproc.cc
- cc/core/Point.h
- cc/core/Vec.h
- cc/core/core.cc
- cc/modules/face/Facemark.cc
- cc/modules/face/FacemarkLBFParams.h
- cc/modules/features2d/features2d.cc
- cc/modules/imgproc/Contour.cc
- test/tests/core/core.test.js
Mainly:
- `int` -> `uint`
- `Nan::MakeCallback` -> `Nan::AsyncResource`
Also add a test to make sure the `type` names added in `AsyncResource` are exposed when `async_hooks` is available.
> fix some compiling warnings

- cc/core/core.cc
- cc/core/core.h
- lib/typings/cv.d.ts
- test/tests/core/core.test.js
Including: `getNumThreads`, `setNumThreads`, `getThreadNum`
Fixes: #368
> src: add threads related API

- .travis.yml
Do testing on `8` `10`  and `stable`.
> ci: test on different versions of node

- cc/modules/dnn/Net.cc
- cc/modules/dnn/Net.h
- cc/modules/dnn/NetBindings.h
- cc/modules/dnn/dnn.cc
- cc/modules/dnn/dnn.h
- cc/modules/dnn/dnnBindings.h
- examples/dnnDarknetYOLORealTimeObjectDetection.js
- examples/dnnTensorflowObjectDetection.js
>  add new DNN Net bindings and improve examples

- binding.gyp
- cc/core/Mat.cc
- cc/core/MatXimgproc.cc
- cc/core/MatXimgproc.h
- cc/core/MatXimgprocBindings.h
- examples/guidedFilter.js
- lib/typings/Mat.d.ts
- test/tests/core/Mat/Mat.test.js
- test/tests/core/Mat/ximgprocTests.js
add guidedFilter guidedFilterAsync
Thanks
> add guidedFilter guidedFilterAsync

- package.json
Update to include https://github.com/justadudewhohacks/npm-opencv-build/pull/28
> Update opencv-build to 0.0.17

- lib/typings/MultiTracker.d.ts
> multiTracker.update outputs an array of Rect

- binding.gyp
- cc/core/HistAxes.cc
- cc/core/HistAxes.h
- cc/core/core.cc
- cc/core/core.h
- cc/imgproc/imgproc.cc
- cc/imgproc/imgproc.h
- cc/imgproc/imgprocBindings.h
- lib/src/deprecations.js
- lib/src/index.js
- lib/typings/cv.d.ts
- test/tests/imgproc/imgprocTests.js
Fixes #407
Refactored calcHist from old `NAN_METHOD` to be class type `CvBinding`
> refactor calcHist and add calcHistAsync

- README.md
Sample app with express & WebSockets to live stream video and transformations
> Sample app with express & websockets

- lib/typings/cv.d.ts
Added Point3 data and in the centers return type in kmeans method
> Add typescript definition for kmeans Point3 argument and return type

- lib/typings/Mat.d.ts
- lib/typings/cv.d.ts
- Add function definition
- getTextSize
- getTextSizeAsync
- Fix function putText parameters order
-  thickness <> lineType
> Fix function parameters + add typescript definition

- lib/typings/TrackerMOSSE.d.ts
> TrackerMOSSE classname fix

- lib/typings/Mat.d.ts
Fixes https://github.com/justadudewhohacks/opencv4nodejs/issues/793, I hope the definitions are correct now.
> Fix Mat.drawContours definition.

- README.md
add redirect to @u4/opencv4nodejs
> add redirect to @u4/opencv4nodejs
