cc/modules/ximgproc/SuperpixelSEEDS.cc
cc/modules/ximgproc/SuperpixelSEEDS.h

In SuperpixelSEEDS.iterate(), I just added a call to getLabelContourMask().

Add label contour mask functionality in SuperpixelSEEDS

---

cc/InstanceConverter.h
package-lock.json
package.json
test/tests/core/Mat/calib3dTests.js

attempting to fix randomly segfaulting calib3d tests (drawChessboardCorners, find4QuadCornerSubpix) due to invalid pattern size

Fix segfaulting calib3d tests

---

examples/utils.js

It seems that endless while(1) loops have a detrimental effect on performance: yeilding back control to the V8 event loop to other events via setInterval() is better

avoid tight while loops as they choke the main event loop

---

cc/modules/io/VideoCapture.cc
cc/modules/io/VideoCapture.h
lib/typings/VideoCapture.d.ts
test/tests/modules/io/videoCaptureTests.js

For example, `VideoCapture.setAsync` can be used when seeking through a video via `cap.setAsync(cv.CAP_PROP_POS_MSEC, second / 1000)`.
When you are doing some processing for a couple sets of frames, the processing takes ~60ms and seeking ~50ms, it would be nice to get the first frame and while processing it, seek to the next one, and have it ready for the next iteration of processing.

Add: VideoCapture.setAsync

---

lib/typings/CascadeClassifier.d.ts

In the typings, levelWeights is misspelled as levelWeigths with the T and the H switched.

Fix spelling mistake in typings

---

binding.gyp
cc/core/CustomAllocator.cc
cc/core/CustomAllocator.h
cc/core/Mat.cc
cc/core/Mat.h
cc/core/core.cc
cc/core/core.h

This ensures that JS always knows (close enough) what memory is in use by native Mat objects, and keeps memory under control automagically.
Whenever a mat is allocated, the custom allocator notes the amount of ram allocated.
Whenever a mat is released,  the custom allocator notes the amount of ram freed.
Node can only be told about the memory changes in the main NodeJS thread; so every allocation/deallocation TRIES to inform node, but does not if not on the main thread.  Also, on new Mat, the reconciliation function is called - this catches allocation which have been done inside an Async process, where a Mat is returned (since most fns return the native cv::mat, which is wrapped in a new JSMat in the main thread).

Add CustomAllocator for Mat.

---

lib/typings/VideoCapture.d.ts

get() was defined as returning void, which is not correct, it results in the following error
there is a workaround, but it would be best if this was not needed

Changed return value of get()

---

appveyor.yml
binding.gyp
cc/CustomMatAllocator.cc
cc/CustomMatAllocator.h
cc/ExternalMemTracking.cc
cc/ExternalMemTracking.h
cc/core/Mat.cc
cc/core/Mat.h
cc/core/core.cc
cc/core/core.h
cc/opencv4nodejs.cc
ci/test/script/run-test.sh
lib/opencv4nodejs.js
test/dut.js
test/externalMemTracking/other/index.test.js
test/externalMemTracking/testDefaultDisabled.js
test/externalMemTracking/testDisableWithEnv.js
test/globals.js
test/package.json

Follow up of #208. 
Mainly did two changes:
1. Move initialization of CustomMatAllactor and methods for retrieving mem metrics and enabling/disabling external mem tracking at runtime to ExternalMemTracking, to have everything in one place and keep logic seperate from Mat and Core, which are mainly for implementing bindings to the OpenCV API + all preprocessor directive checking in a single file mainly.
2. External memory tracking is now enabled by default and the preferred way of disabling it, is via environment flag `OPENCV4NODEJS_DISABLE_EXTERNAL_MEMTRACKING`, which still allows to disable the feature without recompiling, but once at the time of requiring the package instead of arbitrarily at runtime.
For now it is still possible to arbitrarily enable/disable the feature via …

External mem tracking followup

---

cc/modules/calib3d/calib3d.cc
test/tests/modules/calib3d.test.js

As discussed in #238, I changed findHomography to return an output mask.   
It now returns an array [homographyMatrix, outputMask] and can be used in nodejs as follows:
```
let [homography, mask] = cv.findHomography(matched1, matched2, { method: cv.RANSAC, ransacReprojThreshold: 5 });
```
Don't know if the implementation is ideal, I'm no C++ expert 🤷‍♂️

return mask from findHomography

---

lib/typings/Mat.d.ts
lib/typings/cv.d.ts
package-lock.json
package.json

This is the pull request to following issue: https://github.com/justadudewhohacks/opencv4nodejs/issues/233
Fixes the typings for `imdecode`, `imdecodeAsync`, `imencode`, `imencodeAsync`, `Mat constructor` with buffer, `Mat.getData` and `Mat.getDataAsync` with the Node.js Buffer interface.
I checked your general project for `node::buffer` and `Nan::NewBuffer` and found them only in this places, so I hope it should be all places regarding Buffers.

Fixed imdecode, imencode and Mat Buffer typings

---

cc/core/Mat.cc

Regarding #259 
Ideally I'd also like to support `getDataAsArray`, but this looked like the simplest workaround.

Allow get's on 3D matrices

---

README.md

No mention was yet made regarding the installation errors that may occur if a user attempts to install opencv4nodejs onto the Docker image, so I propose adding a small change to notify users of the likelihood of said errors and two workarounds.

Added Note on Docker Usage

---

cc/modules/imgproc/Contour.cc
cc/modules/imgproc/Contour.h
lib/typings/Contour.d.ts
test/tests/modules/imgproc/contourTests.js

Currently approxPolyDP returns Point []
This is a problem, since we lose Contour methods. So I added the approxPolyDPContour method

add approxPolyDPContour

---

cc/opencv4nodejs.cc

This tiny change fixes
```
\node_modules\opencv4nodejs\cc\opencv4nodejs.cc(63): error C2653: 'Core': is not a class or namespace name
\node_modules\opencv4nodejs\cc\opencv4nodejs.cc(63): error C3861: 'Init': identifier not found 
```
when running `electron-rebuild` with `electron@3.0.0-beta.2`.

Fix electron-rebuild for Electron 3

---

cc/modules/tracking/Tracker.cc

Tracker.update() now returns NULL if object is not found rather than always returning a Rect

Fixed issue #369

---

binding.gyp

avoid error "ld: library not found for -lstdc++"
see https://github.com/opencv/opencv/pull/8588
>   SOLINK_MODULE(target) Release/opencv4nodejs.node
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X > 10.9 [-Wdeprecated]
> ld: library not found for -lstdc++
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [Release/opencv4nodejs.node] Error 1

Set MACOSX_DEPLOYMENT_TARGET to 10.9 for Mojave

---

cc/core/Mat.cc
test/tests/core/Mat/Mat.test.js

src: return when throwing errors

---

cc/core/Point.h
cc/core/core.cc
test/tests/core/core.test.js

Hello @justadudewhohacks,
I did a fix for #379 + unit test.
The example of https://github.com/justadudewhohacks/opencv4nodejs/issues/379#issue-350401307 won't work, cause I think kmeans should only accept `Point3` as input and not `Vec3`.
Example
```js
const { labels, centers } = cv.kmeans(
[
new cv.Point3(255, 0, 0),
new cv.Point3(255, 0, 0),
new cv.Point3(255, 0, 255),
new cv.Point3(255, 0, 255),
new cv.Point3(255, 255, 255)
],
2,
new cv.TermCriteria(cv.termCriteria.EPS | cv.termCriteria.MAX_ITER, 10, 0.1),
5,
cv.KMEANS_RANDOM_CENTERS
);
```
Please share your feedbacks
By the way, thank for this lib, i'm just starting to look inside but it looks better organised than node-opencv.

Add Point3 possibilty to kmeans

---

lib/typings/VideoWriter.d.ts

TSC complains about missing fourcc() on VideoWriter type; export as static instead of instance method.

Export fourcc() as static.

---

lib/typings/Mat.d.ts

Hi!
Looks like the Mat class in TS definitions doesn't have .release() defined

Fix: TS: added missing Mat.release fn definition

---

cc/modules/tracking/Trackers/TrackerKCFParams.cc
cc/modules/tracking/Trackers/TrackerKCFParams.h
lib/typings/TrackerKCFParams.d.ts
test/tests/modules/tracking/trackerParamTests.js

Adding `detect_tresh` in KCF Params (see https://docs.opencv.org/3.4/db/dd1/structcv_1_1TrackerKCF_1_1Params.html#af7c297a918719441a448181626488eb0)

Tracking kcf detect tresh

---

README.md

[justadudewhohacks/npm-opencv-build](https://github.com/justadudewhohacks/npm-opencv-build) has been upgraded to use TypeScript in justadudewhohacks/npm-opencv-build#30.
The link for the default OpenCV compilation flags for autobuild points to the old location, which doesn't exist anymore on the master branch.
This commit updates the link to the new TypeScript location.

Correct README link to default autobuild flags

---

package.json

Currently the build process uses all cores and 100% of available CPU when building OpenCV itself, and then drops to a single core when it hits `node-gyp` because that uses a single core by default. This PR simply tells `node-gyp` to use all available cores when building. I saw a 20% decrease in build time from this, and I expect the CI builds will show something similar for this PR.

Use all available core for node-gyp build

---

.travis.yml

Seems like 12 should be the value for `LATEST_STABLE_NODEJS_VERSION` unless I'm misunderstanding it.

Node 12 as latest stable version for CI

---

lib/typings/cv.d.ts

`cv.moveWindow` is implemented by this project but not defined in typings.

Add missing `cv.moveWindow` type definition

---

cc/core/coreUtils.h
lib/typings/Mat.d.ts
test/tests/core/Mat/operatorTests.js

Add `Mat.inv()` to invert a matrix

feat: Mat.inv()

---

cc/io/io.cc
cc/io/io.h
lib/typings/cv.d.ts

Needed on windows (and maybe other systems?) to capture special buttons (like arrow keys).
See for example here: https://stackoverflow.com/questions/45580975/opencv-handling-arrow-keys-with-waitkey-function

add waitKeyEx method

---

cc/core/Mat.cc

Whenever I called splitChannelsAsync my application would crash silently.
I have not tested this change, but I suspect it will fix the problem.

Fix SplitChannelsAsync

---

lib/typings/Mat.d.ts

- Removes duplicated constructors and methods with redundant polymorphism, since all the parameters and return types is equal.
- Fixes `accumulateProductAsync` and `meanAsync` spacing

Remove duplicate methods
